### ISSUE TITLE
[Issue] - Repository image assets organization

### ISSUE THREAD

**Issue by rodgeraraujo** [rodgeraraujo/Pokedex#21]
# 🚀 Feature request

**Context**

Added some Issues templates in the `.github` folder, which was previously used to save images used in the repository's README. The idea would be to move these files, to a folder named better for it like `assets` at the root of the repository.

<img width="312" alt="Screen Shot 2021-10-18 at 11 31 26 AM" src="https://user-images.githubusercontent.com/20842252/137751515-8605c444-a6b4-49b4-85a4-2cc8a7588e8a.png">

After moving the images to the `assets` folder, make sure the locations that make use of them are working correctly.

> Remember this folder does not refer to assets used within the application.

**Comment by rodgeraraujo** [comment]
Sure @sharonibose

**Comment by juniomatias01** [comment]
could you assign me this issue?

**Comment by rodgeraraujo** [comment]
Sure @juniomatias01
